apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-sample-service9"
  annotations:
    jenkins.io/job-full-name: default:sample/backstage-sample-service9
spec:
  type: service
  owner: user:bobo
  lifecycle: lab
